// Code generated by sqlc. DO NOT EDIT.
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const createAccounts = `-- name: CreateAccounts :exec
INSERT INTO accounts (
    owner,
    balance,
    currency,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?
)
`

type CreateAccountsParams struct {
	Owner     string       `json:"owner"`
	Balance   int64        `json:"balance"`
	Currency  string       `json:"currency"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateAccounts(ctx context.Context, arg CreateAccountsParams) error {
	_, err := q.db.ExecContext(ctx, createAccounts,
		arg.Owner,
		arg.Balance,
		arg.Currency,
		arg.CreatedAt,
	)
	return err
}
